#SPDX-License-Identifier: MIT-0
---
# tasks file for ec2
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "ansible-instance"
    # key_name: "prod-ssh-key"
    # vpc_subnet_id: subnet-013744e41e8088axx
    instance_type: "{{ type }}"
    security_group: default
    region: eu-west-2      
    network:
      assign_public_ip: true
    image_id: ami-018ff7ece22bf96db
    tags:
      Environment: Testing
